version: '2'
services:
    craftbeerstore-app:
        image: craftbeerstore
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/craftbeerstore?useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://craftbeerstore-elasticsearch:9200
        ports:
            - 8080:8080
#    craftbeerstore-mysql:
#        extends:
#            file: mysql.yml
#            service: craftbeerstore-mysql
    craftbeerstore-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: craftbeerstore-elasticsearch
