export const enum EstadoLote {
  EN_PROCESO = 'EN_PROCESO',
  PLANIFICADO = 'PLANIFICADO',
  COCCION = 'COCCION',
  FINALIZADO = 'FINALIZADO',
  ANULADO = 'ANULADO',
  FERMENTACION = 'FERMENTACION',
  MADURACION = 'MADURACION',
  ENVASADO = 'ENVASADO'
}
